#
# Spring Boot 全局配置
#
spring:
  # DataSource属性配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/puppet?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  mvc:
    # 默认视图属性配置
    view:
      prefix: /WEB-INF/
      suffix: .jsp
#
# Spring Boot 内置Tomcat端口配置
#
server:
  port: 80
#
# 权限模块配置（此处关闭权限主要为了actuator监控模块正常使用）
#
management:
  security:
    enabled: false