spring:
  profiles: development
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/puppet?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root