#
# Spring Boot 全局配置
#
spring:
  # DataSource属性配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/puppet?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  mvc:
    # 默认视图属性配置
    view:
      prefix: /WEB-INF/
      suffix: .jsp
    # 根据后缀名实现多种视图解析
    viewManager:
      # 启用后缀名作为返回视图类型标识。默认为true
      favorPathExtension: true
      # 忽略请求头中的回调申明，仅按后缀名判定返回视图类型。 默认为false
      ignoreAcceptHeader: true
      # 启用参数申明返回视图类型。默认为true
      favorParameter: false
      # 默认解析类型
      defaultContentType: text/html
#
# Spring Boot 内置Tomcat端口配置
#
server:
  port: 80
#
# 原有权限模块配置（此处关闭权限主要为了actuator监控模块正常使用）
#
management:
  security:
    enabled: false
#
# Shiro权限模块配置
#
shiro:
  filter:
    loginUrl: /l/tologin
    successUrl: /a/index
  cookie:
    name: remeberMe
    # cookie生效时间30天 ,单位秒
    maxAge: 259200

